### ISSUE TITLE
[Question] User names in the deploy section in the .travis.yml file

### ISSUE THREAD

**Issue by neomatrix369** [picknmix/picknmix#63]
* Pick n Mix version: n/a
* Python version: n/a
* Operating System: na/

### Description

I had a look at this section of the `.travis.yml` and it seems incorrect, the last parts, see below:

```yaml
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Cheukting     <=== shouldn;t this be picknmix? or are you still using Cheukting on pypi?
  password:
    secure: <snipped>
  on:
    tags: true
    repo: Cheukting/picknmix   <=== shouldn;t this be picknmix/picknmix
    python: 3.7
```
Maybe I'm wrong.

### What I Did

N/A
